CREATE TABLE Users(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(200) NOT NULL UNIQUE,
	email VARCHAR(200) NOT NULL UNIQUE,
	password VARCHAR(200) NOT NULL
);

CREATE TABLE Tasks(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	content VARCHAR(500) NOT NULL,
	user_id INTEGER FOREIGN KEY REFERENCES Users(id)
);

